### PR TITLE
WIP: Tract experiments

### PR DESCRIPTION
**Pull request by Rikorose**
Export model via onnx, create rust only runnable using [tract](https://github.com/sonos/tract).

### CODE REVIEW

**Comment by JulienBalianSonos** [comment]
Hello Hendrik,
I would like to first congrats and thank you for the great research you have published and open-sourced with DeepFilterNet (1 & 2).

We have been impressed by the quality and the results of your work (our internal retraining/benchmarks with this solution seems promising).

We would like to go further and understand in-depth the on-device consumption of such solution.

Seeing that you already almost did the work in this PR with tract inference engine in full rust:

    I was wondering if you could expand the blockers that lead you to let this branch stale.
    I saw your comments here: 

    https://github.com/Rikorose/DeepFilterNet/issues/77 and was willing to better understand how we could help on this ?

Also, a rebase or merge from main into this branch seems needed to revive this branch, do you confirm ?

**Comment by Rikorose** [comment]
Hi Julien,

thanks for your interest in DeepFilterNet. This is an old branch focusing on DeepFilterNet[1]. The first stage (ERB mask only) works. However, the second stage (Deep Filtering, DF) has a bug wrt. latency. During training/offline usage the whole mask is applied to the signal. Thus, the second stage get's the full pre-enhanced signal. During real-time inference however, we can only enhance the signal until `t0 - conv_lookahead`. DF additionally needs an additional latency of `df_lookahead`, which is not intended, or operate on a only partially pre-enhanced signal (where `df_order-df_lookahead` frames are pre-enhanced, and `df_lookahead` frames are still noisy).
A possible fix for this can be
a) Don't use any lookahead for convolutions and DF.
b) Change the model, so that DF is trained to operate on noisy data and use the 1. stage only for the upper frequencies.
c) Allow an overall larger latency and work with 2 ring buffers (1 for noisy spectrogram and 1 for stage 1 spectrogram output).

I am currently working towards a) and b) for DeepFilterNet2 (on a new branch) and retrain a model but cannot give an ETA.

**Comment by JulienBalianSonos** [comment]
Thanks for your quick answer, I do better understand the issues now.
Significant latency would be problematic for our use case as well.

Out of curiosity with a `conv_lookahead=2` (as in default) what would be the latency in milliseconds today with DF2 ?

Regarding your ongoing work on a fully causal arch, that's exciting news :) !

No worries with an ETA,
Once you reach a new stable causal architecture,
could just you please ping me  (@(JulienBalianSonos)) or Kali (@(kali))  ?
If you still wish to build an inference in full rust, we will be happy to solve any issue regarding `tract` or give a hand on inference side.

**Comment by Rikorose** [comment]
A lookahead of 2 corresponds to a latency of 2 frames (1 frame = 10 ms). You can retrain the models with lower frame size and fft size if you need a lower latency. The minimum I tested was an FFT size of 4ms and a hop size (frame size) of 1ms. This however reduces the noise reduction performance and increases the computational requirements since the model needs to be run 1000 times per second (DeepFilterNet2 needs 100 evaluations per second).
What are your latency requirements?

Regarding tract. I still plan to work on this. I am not sure if I can fully utilize one cpu core, since the model may be too complex (permutations, slices, etc). I tried to reduce it compared to DeepFilterNet1, but am not sure how to measure performance nicely to figure out some bottlenecks. Also regarding allocations: Tract requires a clone of the current input features. I have not measured it, but if feels 'costly' to do this 1000 times per second. Is there a way to avoid this?

**Comment by kali** [comment]
Answering about the input feature cloning here... tract was not designed to run at this kind of frequencies, so no general effort was made to reduce allocations. The one in the input is really not a big problem in itself: there are dozens of them all over the place. 

DSP community is traditionally very cautious about allocation, so DSP apps often pre-allocate everything. That's not how tract is written. tract assumes it runs in a runtime that feature a very modern allocator like jemalloc. In this context, allocations are cheaper than they used to be a couple of decades ago (or still are under windows default allocator). Changing that is a huge amount of work, I would only consider it after cautious profiling and auditing.

From our experience, allocations do not get problematic (as in, not showing outrageously in profiles) at running frequencies like 100Hz (10ms frames). We never really try to go below that. But the lower you'll get, the most likely there may show up... But really the on in run() in the least of your concerns here.

**Pull request closed without merging**
