### PR TITLE
Add C API

### PR DESCRIPTION
**Pull request by Rikorose**

### CODE REVIEW

**Comment by Rikorose** [comment]
```bash
cargo install cargo-c
cargo cinstall --release --destdir /tmp/staging-df -p deep_filter
```

Generates the following header:

```c
#define DEEP_FILTER_MAJOR 0
#define DEEP_FILTER_MINOR 3
#define DEEP_FILTER_PATCH 2


#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct DFState;

extern "C" {

/// Create a DeepFilterNet Model
///
/// Args:
///     - path: File path to a DeepFilterNet tar.gz onnx model
///     - atten_lim: Attenuation limit in dB.
DFState *df_create(const char *path, float atten_lim);

/// Get DeepFilterNet frame size in samples.
uintptr_t df_get_frame_length(DFState *st);

/// Get DeepFilterNet frame size in samples.
///
/// Args:
///     - lim_db: New attenuation limit in dB.
void df_set_atten_lim(DFState *st, float lim_db);

/// Processes a chunk of samples.
float df_process_frame(DFState *st, float *input, float *output);

/// Free a DeepFilterNet Model
void df_free(DFState *model);

} // extern "C"

```

**Comment by tingyang01** [comment]
Hello.
I am trying this C API.
#include <iostream>
#include "deep_filter.h"
#pragma comment(lib,"WS2_32")


int main()
{
	float atten_lim = 12.0;
	const char* onnxPath = "models/DeepFilterNet2_onnx.tar.gz";
	DFState *_dfModel = df_create(onnxPath, atten_lim);
	//df_free(_dfModel);
	std::cout << "Hello World!\n";
}
But I am getting this error on running the execution file:
J:\Work\2017\SVNWork\Upwork\SignalProcessing\DeepFilterNet\DeepFilterNetWindows\x64\Release>DeepFilterNetWindows.exe
thread '<unnamed>' panicked at 'not yet implemented', C:\Users\tings\.cargo\registry\src\github.com-1ecc6299db9ec823\tract-hir-0.18.4\src\ops\array\reshape.rs:133:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:111
   3: tract_hir::ops::array::reshape::to_axis_ops
   4: <tract_hir::ops::array::reshape::Reshape as tract_hir::ops::expandable::Expansion>::wire
   5: tract_hir::ops::expandable::<impl tract_hir::infer::rules::InferenceRulesOp for alloc::boxed::Box<dyn tract_hir::ops::expandable::Expansion>>::to_typed
   6: tract_hir::infer::rules::<impl tract_hir::infer::ops::InferenceOp for O>::to_typed
   7: ZN512_$LT$$LT$tract_core..model..graph..Graph$LT$tract_hir..infer..fact..InferenceFact$C$alloc..boxed..Box$LT$dyn$u20$tract_hir..infer..ops..InferenceOp$GT$$GT$$u20$as$u20$tract_hir..infer..model..InferenceModelExt$GT$..into_typed..ToTypedTranslator$u20$a
   8: tract_core::model::translator::Translate::translate_model
   9: <tract_core::model::graph::Graph<tract_hir::infer::fact::InferenceFact,alloc::boxed::Box<dyn tract_hir::infer::ops::InferenceOp>> as tract_hir::infer::model::InferenceModelExt>::into_typed
  10: deepfilter::tract::DfTract::new
  11: df_create
  12: main
             at j:\work\2017\svnwork\upwork\signalprocessing\deepfilternet\deepfilternetwindows\deepfilternetwindows\deepfilternetwindows.cpp:13
  13: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  14: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  15: BaseThreadInitThunk
  16: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Thanks

**Comment by Rikorose** [comment]
This is unrelated to the c api. Can you open a new issue for this and try to reproduce it in pure rust?

**Comment by tingyang01** [comment]
ok

**Comment by tingyang01** [comment]
But this is the error on running the API version.
Could you share your idea?

**Pull request merged**
